### ISSUE TITLE
 Invalid filter "PascalCase" on line 28 in file 

### ISSUE THREAD

**Issue by elirehema** [NetanelBasal/vue-generate-component#24]
I can't create vue component using `vgc ComponentName`.

I don't know if command was changed for last two hours release but the error log is as shown down here.
```
**eli@eli:~/Documents/user/eLog/Onn/src/pages$ vgc chartsPage**

/usr/local/lib/node_modules/vue-generate-component/node_modules/swig/lib/utils.js:183
  throw new Error(message + '.');
  ^

Error: Invalid filter "PascalCase" on line 28 in file /usr/local/lib/node_modules/vue-generate-component/dist/blueprints/component/temp.script.extension.
    at Object.exports.throwError (/usr/local/lib/node_modules/vue-generate-component/node_modules/swig/lib/utils.js:183:9)
    at TokenParser.parseToken (/usr/local/lib/node_modules/vue-generate-component/node_modules/swig/lib/parser.js:197:15)
    at /usr/local/lib/node_modules/vue-generate-component/node_modules/swig/lib/parser.js:86:12
    at Object.exports.each (/usr/local/lib/node_modules/vue-generate-component/node_modules/swig/lib/utils.js:45:11)
    at TokenParser.parse (/usr/local/lib/node_modules/vue-generate-component/node_modules/swig/lib/parser.js:76:11)
    at parseVariable (/usr/local/lib/node_modules/vue-generate-component/node_modules/swig/lib/parser.js:487:18)
    at /usr/local/lib/node_modules/vue-generate-component/node_modules/swig/lib/parser.js:635:15
    at Object.exports.each (/usr/local/lib/node_modules/vue-generate-component/node_modules/swig/lib/utils.js:45:11)
    at Object.exports.parse (/usr/local/lib/node_modules/vue-generate-component/node_modules/swig/lib/parser.js:624:9)
    at exports.Swig.parse (/usr/local/lib/node_modules/vue-generate-component/node_modules/swig/lib/swig.js:354:19)


**eli@eli:~/Documents/user/eLog/Onn/src/pages$ vgc chartpage**
/usr/local/lib/node_modules/vue-generate-component/node_modules/swig/lib/utils.js:183
  throw new Error(message + '.');
  ^

Error: Invalid filter "PascalCase" on line 28 in file /usr/local/lib/node_modules/vue-generate-component/dist/blueprints/component/temp.script.extension.
    at Object.exports.throwError (/usr/local/lib/node_modules/vue-generate-component/node_modules/swig/lib/utils.js:183:9)
    at TokenParser.parseToken (/usr/local/lib/node_modules/vue-generate-component/node_modules/swig/lib/parser.js:197:15)
    at /usr/local/lib/node_modules/vue-generate-component/node_modules/swig/lib/parser.js:86:12
    at Object.exports.each (/usr/local/lib/node_modules/vue-generate-component/node_modules/swig/lib/utils.js:45:11)
    at TokenParser.parse (/usr/local/lib/node_modules/vue-generate-component/node_modules/swig/lib/parser.js:76:11)
    at parseVariable (/usr/local/lib/node_modules/vue-generate-component/node_modules/swig/lib/parser.js:487:18)
    at /usr/local/lib/node_modules/vue-generate-component/node_modules/swig/lib/parser.js:635:15
    at Object.exports.each (/usr/local/lib/node_modules/vue-generate-component/node_modules/swig/lib/utils.js:45:11)
    at Object.exports.parse (/usr/local/lib/node_modules/vue-generate-component/node_modules/swig/lib/parser.js:624:9)
    at exports.Swig.parse (/usr/local/lib/node_modules/vue-generate-component/node_modules/swig/lib/swig.js:354:19)

```

https://github.com/NetanelBasal/vue-generate-component/blob/master/lib/blueprints/component/temp.script.extension#L28

**Comment by NetanelBasal** [comment]
Oh, I see. I will fix it later. In the meantime, use the old version.

**Comment by NetanelBasal** [comment]
Fixed.

**Comment by elirehema** [comment]
@NetanelBasal i tried to run `npm install -g vue-generate-component` and `npm install  vue-generate-component --save` in my project. But when i try to create component with `vgc myComponentName` i got the same error

**Comment by radfahrer** [comment]
This seems to be happening again in 3.0.0

**Comment by NetanelBasal** [comment]
Can you please create a PR with the fix?

**Comment by elirehema** [comment]
@NetanelBasal are you expecting to implement composition api in this library.

**Comment by NetanelBasal** [comment]
I'm open to PR.
